### PR TITLE
I don't know what to say.

### PR DESCRIPTION
**Pull request by Heyter**

### CODE REVIEW

**Comment by OmniSyzygy** [comment]
Didn't know anyone was even looking at this or making any progress. Did you want to talk about this?

**Comment by Heyter** [comment]
>Did you want to talk about this?

About what?
You can merge this?

**Comment by OmniSyzygy** [comment]
Yes, I can.

Also apologies, I work nights and had a busy schedule recently. Just wanted to get your aim regarding these updates. Were you just bored and wanted to work on something or are you actually bringing this up to speed?

There's already a successor to this project that's been in-dev for 6 months is why I ask.

**Comment by Heyter** [comment]
just bored and wanted to work on something.
Has anyone already developed it?

**Comment by OmniSyzygy** [comment]
If you'd like, it's easier to reach me via Discord or Steam.

Discord - OmniSyzygy#2500
Steam - https://steamcommunity.com/id/OmniSyzygy/

Otherwise on Raindrop no, you're the only person who's worked on it in a year or so.

**Comment by Heyter** [comment]
Accept http://steamcommunity.com/id/meow1337

**Review by ghost — APPROVED** [review]

**Pull request merged**
